### ISSUE TITLE
Handling the exception of not available tokens for the specific day

### ISSUE THREAD

**Issue by Konstantina-Lazaridou** [EventRegistry/event-registry-python#54] opened 2020-10-06 16:38 UTC
Hi,
I am getting this exception message:
```
Event Registry exception while executing the request:
You have used all available tokens for unsubscribed users from this IP address. In order to continue using Event Registry please subscribe to a paid plan.
The request will be automatically repeated in 3 seconds...
```

when I iterate over the result of my search query, but I cannot find where exactly this exception happens internally (and I also cannot handle it properly because it does not appear to be of the type `Exception`).

This is how I iterate over the response of my query:
```
er = EventRegistry( ... )
 query_result = query.execQuery(er, ...)
        for article in query_result:
            print(article)  # shows the above-mentioned message

```

I would like to handle this exception and stop calling the API, and then try the next day. Apparently the method `er.getRemainingAvailableRequests` shows the remaining tokens in general, not for the specific day and this one `er.getDailyAvailableRequests` just shows general information about the default tokens in event registry.

How can I get the remaining daily tokens in Python? I also don't see a relevant HTTP status code for the Rest API: https://eventregistry.org/documentation?tab=introduction

**Comment by gregorleban** [comment] 2020-10-21 16:52
Hi Konstantina,

thank you for your reported issue. Yes, we have recently changed how the request limit is reported (previously we returned status 200 with an error message and changed to using status codes to report this) and this change was not yet reflected in the Python SDK. We have now changed that so that status codes 204, 400, 401 and 403 are now raised as exceptions that you can check and respond to in your code. The meaning of these status codes is described on our [documentation page](http://eventregistry.org/documentation). To get these changes, please update to the latest version of the Python SDK.

For free users, there is a daily limit of 1000 used tokens and a total of 2000 tokens. The daily number of used tokens for the user is not something that is available over the API as this is something that is only relevant for the free users (the paid users don't have any limit).

**Comment by mananbhalodia** [comment] 2023-12-27 06:22
Hello, I seem to be getting the error mentioned above however I have not hit the limit for the free account, I am well bellow around 47 tokens used this month. 

This is the stack trace - 

`
DEFAULT 2023-12-27T06:13:14.510540Z for article in q.execQuery(er, sortBy="socialScore", maxItems=50):
DEFAULT 2023-12-27T06:13:14.510545Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/QueryArticles.py", line 394, in __next__
DEFAULT 2023-12-27T06:13:14.510549Z self._getNextArticleBatch()
DEFAULT 2023-12-27T06:13:14.510555Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/QueryArticles.py", line 374, in _getNextArticleBatch
DEFAULT 2023-12-27T06:13:14.510559Z res = self._er.execQuery(self)
DEFAULT 2023-12-27T06:13:14.510564Z ^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-12-27T06:13:14.510569Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/EventRegistry.py", line 221, in execQuery
DEFAULT 2023-12-27T06:13:14.510574Z respInfo = self.jsonRequest(query._getPath(), allParams, allowUseOfArchive = allowUseOfArchive)
DEFAULT 2023-12-27T06:13:14.510578Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-12-27T06:13:14.510584Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/EventRegistry.py", line 302, in jsonRequest
DEFAULT 2023-12-27T06:13:14.510589Z raise self._lastException or Exception("No valid return data provided")
DEFAULT 2023-12-27T06:13:14.510594Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/eventregistry/EventRegistry.py", line 278, in jsonRequest
DEFAULT 2023-12-27T06:13:14.510597Z raise Exception(respInfo.text)
DEFAULT 2023-12-27T06:13:15.553164Z Exception: You have used all available tokens for unsubscribed users from this IP address. In order to continue using Event Registry please subscribe to a paid plan.
`
This only happens when I run the code through Google Cloud Functions; when I run locally I am able to hit the API just fine.

**Comment by gregorleban** [comment] 2023-12-27 09:46
duplicate of https://github.com/EventRegistry/event-registry-python/issues/65

**Closed by gregorleban** 2023-12-27 09:46 UTC
